name: flutter_pocket_money_manage_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations: # 多言語ライブラリの本体
    sdk: flutter 

  flutter_riverpod: ^2.1.1
  flutter_speed_dial: ^6.2.0
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2
  syncfusion_flutter_calendar: ^20.3.60
  table_calendar: ^3.0.8

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.16
  freezed:
  objectbox_generator:
  pedantic_mono:

flutter_native_splash:
  color: '#add8e6'
  image: 'assets/splash/splash.png'
  color_dark: '#262626'
  image_dark: 'assets/splash/splash.png'
  fullscreen: true
  android_12:
    icon_background_color: '#add8e6'
    image: 'assets/splash/splash_android12.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets/splash/splash_android12.png'

flutter:
  uses-material-design: true

  assets:
    - assets/