name: flutter_pocket_money_manage_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.1.1
  flutter_slider_drawer: ^2.1.2
  freezed_annotation: ^2.2.0
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2
  table_calendar: ^3.0.8

dev_dependencies:
  build_runner: ^2.0.0 
  flutter_lints: ^2.0.0
  freezed:
  objectbox_generator:
  pedantic_mono:

flutter:
  uses-material-design: true